{
 "title": "Overview",
 "tags": [ "templated" ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Quantity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "request_quantity", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "response_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "And Something Else",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "and_something_else", "legendFormat": "__auto" }
   ]
  }
 ]
}